use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'

target 'TestPopView_Example' do
  pod 'TestPopView', :path => '../'

  target 'TestPopView_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
